using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using Beamable;
using Beamable.Api.Autogenerated.Accounts;
using UnityEngine;

namespace Backend.Managers
{
    public class BeamableManager : MonoBehaviour, IBackendManager
    {
        public static BeamableManager Instance { get; private set; }

        private BeamContext _beamableContext;
        
        

        public void InstantiateSingleton()
        {
            if (Instance is null)
            {
                Instance = this;
                DontDestroyOnLoad(this);
            }
            else
            {
                Destroy(this);
            }
        }

        void Start()
        {
            InstantiateSingleton();
        }

        void Update()
        {

        }

        public async Task SignIn()
        {
            _beamableContext = BeamContext.Default;
            await _beamableContext.OnReady;
            
            _beamableContext.Accounts.RecoverAccountWithDeviceId();
        }

        public Task SignOut()
        {
            throw new System.NotImplementedException();
        }
    }
}


